### PR TITLE
Fix punctuation and spelling in json file

### PR DESCRIPTION
**Pull request by jdebacker**
This PR fixes some grammar and spelling in the default json file.

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
This looks good to me @jdebacker .  Either in this PR or a separate one, can you add a `min` and `max` value to each of the numeric parameters for the purposes of form validation.  Here is an example of where to put those:
```
[
  [
    "btax_betr_corp",
    {
      "long_name": "Corporate Income Tax Rate",
      "notes": "This parameter is the top statutory corporate income tax rate.",
      "description": "Top statutory corporate income tax rate",
      "value": [
        [
          0.35
        ],
     "min": [0.3],
     "max": [0.5]
      ]
    }
  ],
```

**Comment by jdebacker** [comment]
@PeterDSteinberg - added min and max values.

**Comment by MattHJensen** [comment]
@jdebacker, we have been fairly permissive in tax-calculator about letting users enter weird parameter values. Some users, for example, might actually want a corporate rate below 0 or greater than 1. Therefore, oftentimes we give hints with comments about 'typical ranges' rather than putting up guardrails in the validation. 

Currently, we only disallow values that would generate inaccurate tax-calculator results. For example, we don't currently impute itemized deductions to non-itemizers, and so we don't allow users to decrease the standard deduction. 

For an example of our discussions on these issues, see https://github.com/open-source-economics/Tax-Calculator/pull/788#discussion_r68937111 and Martin's followup commit: https://github.com/open-source-economics/Tax-Calculator/commit/ecbf3115b3c0acb4e68ea7648e7c402ddb2b5edd. 

@PeterDSteinberg, will you be using the validation parsing that we use for current_law_policy.json in TC? If that is the case then that file might be helpful for @jdebacker to review. 

@jdebacker, for even more background reading if you would like to see it, [here](https://github.com/open-source-economics/Tax-Calculator/pull/355) is the PR where we first added parameter validation to tax-calculator and [here](https://github.com/open-source-economics/Tax-Calculator/issues/331) is the issue where much of the discussion happened. 

All that said, if you prefer a different style for validation, I don't think it is necessary to follow in TC's footsteps.

**Comment by jdebacker** [comment]
@MattHJensen , I gave fairly large ranges, but didn't allow for negative numbers.  Or rates about 100% - I'll go back and be more permissive because it could make sense here (e.g. with a cash flow tax, the METR on the marginal investment is zero, so you could very well want a statutory rate in excess of 100% since all the burden falls on the supra-normal returns.

But I would be careful with rates of 100%+ for the TC.  I don't see the static results making much sense in that context.  Why work or save when facing such a rate?

**Comment by PeterDSteinberg** [comment]
@MattHJensen and @jdebacker .  Currently B-Tax UI in this PR uses a subset of the functionality in `current_law_policy.json`.  We can add fields as needed.  Most of the validation is the same.

**Comment by jdebacker** [comment]
@PeterDSteinberg Are we set to merge this then?

**Comment by PeterDSteinberg** [comment]
Yes @jdebacker

**Pull request merged**
