### PR TITLE
ensure 'All Investments' at bottom of each /ccc table

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
Make sure the last row is always `All Investments`

### CODE REVIEW

**Comment by jdebacker** [comment]
@PeterDSteinberg Thanks for addressing this.  I think it makes more sense for "All Investments" to be the first row in the table (rather than the last).  Could you make that change before we merge?

**Comment by PeterDSteinberg** [comment]
@jdebacker That should be an easy fix.  I can do it now.

**Comment by PeterDSteinberg** [comment]
@jdebacker Fixed.  See below:
screen shot 2016-12-13 at 4 52 01 pm

**Comment by jdebacker** [comment]
Great - thanks @PeterDSteinberg

**Pull request merged**
