### PR TITLE
Unit testing for calc_z.py

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds unit tests for the functions in `calc_z.py`.

### CODE REVIEW

**Comment by jdebacker** [comment]
@hdoupe  I think this read to go, but before I merge, let me ask - is there anything different you'd do to compare data frames than `assert_frame_equal`?  Anything comparable to `numpy.allclose` that I'm missing?

**Comment by hdoupe** [comment]
I think `assert_frame_equal` is probably your best bet. There's a [`check_less_precise` keyword](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.testing.assert_frame_equal.html) that you may be able to use. 

Another option would be to access the underlying numpy arrays and use `np.allclose` with those.

Unless you start having precision problems, I think that `assert_frame_equal` as you are using it now should do the trick.

**Comment by hdoupe** [comment]
Now that you have the `calc_z.py` module under test coverage, you could experiment with using matrix multiplication instead of all of the loops you are using now. It'll be a lot more fun and less stressful to tinker with this module now that you can be confident you won't break anything by doing so.

**Comment by jdebacker** [comment]
@hdoupe Thanks for these suggestions.  I think I'll keep this for now, but will use the keyword arg if needed in future (wish I had noted that before since I was trying to do calculations in Excel as check and there were some rounding differences).

**Pull request merged**
