### PR TITLE
Conda recipe

### PR DESCRIPTION
**Pull request by talumbau**

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
@talumbau Should version in meta.yaml come automatically instead from versioneer.py?

**Comment by talumbau** [comment]
Ah, I usually manually increment. I suppose we could use git tags. I can create an issue to investigate and modify.

**Comment by talumbau** [comment]
or rather, I mean, git macros

**Comment by talumbau** [comment]
see #75

**Comment by talumbau** [comment]
see #75

**Comment by talumbau** [comment]
see #75

**Comment by talumbau** [comment]
see #75

**Comment by talumbau** [comment]
see #75

**Comment by talumbau** [comment]
see #75

**Pull request merged**
