### PR TITLE
Soi Data

### PR DESCRIPTION
**Pull request by bfgard**
Creating a PR for new soi data. I'll resolve the conflicts after class. I just wanted to get this up.

### CODE REVIEW

**Comment by jdebacker** [comment]
@bfgard, this looks good.  

Let's do the following check before we merge - can you compare the asset values from btax master - both the output table by asset and the one by industry - to what you get from this branch.  You should see that the distribution across industries and tax treatment changes, but totals by asset (which were based on asset values from 2013 BEA data).  Also, total assets (summing across asset/industry/tax treatment) in both tables should be the same in this branch as in master.

**Comment by bfgard** [comment]
I'm having trouble finding the data in the master. On my local machine the btax_output_dir (with .csv files for by industry and by asset calcs) is created every time the code is run but it doesn't appear to be on GitHub.

**Comment by jdebacker** [comment]
Switch to master branch and run. Save csv files w unique name. Then switch back to this branch and run. Then you can compare output from the two.

**Comment by bfgard** [comment]
That makes sense to me. I've saved my output, but when I pulled some of the new changes to perform the test it says that I'm missing the puf.csv to correctly run the taxcalculator. Any ideas?

**Comment by bfgard** [comment]
Okay, I ran both the branches and compared the baseline output csv files.

The asset file is largely unchanged. The only difference is the proportion of corporate and non corporate assets. However, when summed together the total amount is the same for all the assets. The total of all the assets (the sum across tax treatment and asset type) did not change. It's something like 3.57x10^13

In the industry file there are more differences. The proportion of corporate and non corporate assets changed as did the summed total by industry. However, the sum of all the assets over all the industries and tax treatments is the same for both files. It's 3.40x10^17.

So there is a difference between the total assets by industry and the total assets by type, but this difference appears in the spreadsheets from both branches. And the difference between the two numbers stays the same for both branches.

**Comment by jdebacker** [comment]
@bfgard, that sounds right. Thanks for doing the check manually. We will need to set up automatic tests for this stuff in the future. I'll merge this when I have some time back at computer. Prob sun or Monday.

**Pull request merged**
