### PR TITLE
Btax

### PR DESCRIPTION
**Pull request by bfgard**
The code that I uploaded yesterday wasn't functional because the package names didn't reflect the renaming of the scripts. I fixed the imports and added a test for checking the outputs of two .pkl files.

### CODE REVIEW

**Comment by talumbau** [comment]
@bfgard @jdebacker I'm a bit concerned that the pickle file here is rendering as text and not binary. Did you develop this on a Windows platform? I think you might want to make sure that you open the file in mode `wb` to make sure that the file is registered as a binary file.

**Comment by bfgard** [comment]
Here is the command I used to store the pickle file. I noticed that some of the .pkl files were appearing as binary files and others were not.

with open(os.path.join(_OUT_DIR, 'final_output.pkl'), 'wb') as handle:
		pickle.dump(CBO_v_OSPC[cols_to_print], handle)

**Comment by bfgard** [comment]
image

One appeared as a binary file and the other didn't, which contributed 2 million changes!

**Comment by bfgard** [comment]
@talumbau I added the .gitattributes file to the main Git folder, and removed the .pkl file. I remade the .pkl file with 'wb' enabled and added it back to the project.

image

On the command line it doesn't show the addition of the .pkl file as creating any additions or deletions, but here on GitHub it still doesn't recognize it as a binary file. Thoughts?

**Comment by talumbau** [comment]
Wow that's weird. I think you've done due diligence here. Looks like a weird Github thing to me.

**Comment by talumbau** [comment]
Hi @bfgard, I noticed your .travis.yml needs a bit more to get going. The basic idea is to consider the Travis-CI environment a completely blank slate. So you'll have to install all the dependencies into the environment each time it runs. This is what we do for OG-USA, for example:

https://github.com/open-source-economics/OG-USA/blob/master/.travis.yml

In the `install:` section, you can see we get the latest miniconda and install the necessary conda packages before running OG-USA:

```
install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pytest scipy numpy pandas matplotlib
  - conda install -n test-environment -c ospc taxcalc
  - conda install -n test-environment numba 
  - source activate test-environment
  - python setup.py install
```

**Comment by bfgard** [comment]
Haha, I've been having a little trouble with this, but this is what I have now:

sudo: false

language: Python
python:
  - "2.7"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pandas numpy
  - conda install 
  - source activate test-environment
  - python setup.py install
# command to run tests
script: cd Python/btax; run check_output.py

I'm still unsure about the line of code needed to actually run the script and which packages I need to include on the install list.

**Comment by bfgard** [comment]
After some trial and error, I think I finally got the Travis CI working. Thanks for the help TJ!

**Comment by talumbau** [comment]
this looks pretty reasonable to me. As a next step, I would suggest setting up the tests with [pytest](http://docs.pytest.org/en/latest/) so you can easily add additional testing beyond what is in `check_output.py`. But, this is working for now, so I am +1 on merging.

**Comment by bfgard** [comment]
I'll take a look at the

**Pull request merged**
