### PR TITLE
test / build for Python 3

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
Python 3 testing and fixes.

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
@jdebacker - This adds Python 3 support.  If you have time to review, try out a couple of interactive examples in Python 2 vs 3 and see if this makes sense to you.

**Comment by jdebacker** [comment]
@PeterDSteinberg Looks good.  Did you test that asset pkl file is the same after these changes?  It ought to be, but we might want to test before merging.  I can do that over the weekend - few deadlines to hit today with other stuff.

**Comment by jdebacker** [comment]
Were you able to compare the values in the two, e.g. by comparing the elements of the data frame in each?  Again, I see some changes with the scripts that load the data needed for Python 3.x compatibility.  Just wanted to be sure nothing unanticipated happening there.

**Comment by PeterDSteinberg** [comment]
@jdebacker Which dataframe would be the best side-by-side comparison to ensure I didn't break anything going to Python 3?  The data that becomes asset pickle?  The changes in the dataframe related code for Python 3 were mainly unicode vs bytes column labels and index values issues.  I don't anticipate problems, but agree it would be good to compare directly.

**Comment by jdebacker** [comment]
@PeterDSteinberg - yes comparing the data frames that become the asset pickle is what I was thinking.  If anything did change going to Python 3, we should be able to see it there.

**Comment by PeterDSteinberg** [comment]
@jdebacker I compared the asset pickle dataframes from Python 2.7 and 3.4 and they were identical.  I made them in separate environments and writing the pickle to csv for pickle-independent check.

The CSV files are too big to upload here.  I'll email them to you.

**Comment by jdebacker** [comment]
Thanks for that check.   I'll merge now.

**Pull request merged**
