### PR TITLE
Deprbranch

### PR DESCRIPTION
**Pull request by bfgard**
This is my second attempt at updating the file structure and creating the btax package.

### CODE REVIEW

**Comment by talumbau** [comment]
I think you also want to add `.DS_Store` to the `.gitignore`. I think that's a pretty common thing to do because so many folks use Mac now.

**Comment by bfgard** [comment]
.DS_Store is in .gitignore on the last line. What does that file do?

**Comment by talumbau** [comment]
Oh I see you are deleting it, that's good. I find this PR hard to review because two things are happening: 1. move a large number of files from one location to another 2. make a package out of some Python files. In a perfect world, these would be separate activities so we could just look at the few Python files you have moved around

Also, I think you are checking the built sphinx documentation right? That is typically not done. The idea is that since sphinx builds docs from code, you keep the code up to date, and then rebuild locally when you want to view documentation. So, my thoughts are that the HTML in _build and below should not be a part of the repo. just my two cents.

**Comment by jdebacker** [comment]
That file keeps track of the settings for the folder it's in (e.g. how the
files are displayed - as a list, icons, etc).

**Comment by bfgard** [comment]
I'll make sure to avoid making such drastic changes in the future and separate different actions into different commits. The code is currently working on my machine.

I removed the html files from the sphinx documentation, and I really would love to learn how that all works.

**Comment by talumbau** [comment]
OK, this is looking pretty good now. A lot of deletes and when you scroll to the bottom of the PR, there's a  fair amount of "renamed without changes" which is good. The actual changes to the Python files looks, as do the new scripts. I say we merge this and then I will attempt to run and verify I can get the same answers as before. If that is good, the next step would be to turn on Travis CI since we already have reference data and a way to evaluate the right answer.

**Pull request merged**
