### PR TITLE
Conda pkg

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
Work in progress to get conda.recipe ready for conda-forge.

### CODE REVIEW

**Comment by jdebacker** [comment]
@PeterDSteinberg I appears there is a Conda package - https://anaconda.org/ospc/btax

Is this PR still relevant?

**Comment by brittainhard** [comment]
@jdebacker this looks like code for setting up a proper conda recipe. It would make it easier to get the new btax versions up onto `anaconda.org`.

**Comment by jdebacker** [comment]
@brittainhard thanks for letting me know.  Guess it is quite relevant.

**Comment by PeterDSteinberg** [comment]
Replaced by #142

**Pull request closed without merging**
