### PR TITLE
Include PT income mtrs separately

### PR DESCRIPTION
**Pull request by jdebacker**
This PR updates the calculation of the marginal tax rate on non-corporate income to account for the separation of PT income from ordinary income in TC (via PR #913).

### CODE REVIEW

**Comment by jdebacker** [comment]
@codykallen , can you look at the computation of the MTR on non-corporate income in the modified filed (`get_taxcalc_rates.py`)?

I'm not finding a rate on non-corporate income (under current law) of 0.367.  In comparison, before this change I was finding a rate of 0.29, your calculation yields a rate of 0.29, and CBO's a rate of 0.33. 

Note, I am using the combined MTR - I don't know what you or CBO use.

**Comment by MattHJensen** [comment]
What year was CBOs number from? If it was pre-2013, then a higher rate today would make sense.

**Comment by jdebacker** [comment]
I'm referring to [this CBO paper](https://www.cbo.gov/sites/default/files/113th-congress-2013-2014/reports/49817-Taxing_Capital_Income_0.pdf), which uses 2014 law.  So I don't think it's anything in tax law, but rather something in the construction of the average.

**Comment by jdebacker** [comment]
Upon further inspection, I find that excluding fica taxes (so using mtr_iit), the rate on non-corporate income is 0.334 - very close to CBO's 0.331.  

Is this the right rate to use?  Does the iit rate account for the NIIT?

cc @codykallen @MattHJensen

**Comment by MattHJensen** [comment]
That's great. NIIT  is in IIT.

**Comment by jdebacker** [comment]
Thanks @MattHJensen.  I'll go with IIT rates.

**Comment by codykallen** [comment]
NIIT is in IIT, but that shouldn't matter anyway, since it does not apply to Sch C or earned Sch E income (S corp and partnership).

**Comment by jdebacker** [comment]
@codykallen - wouldn't passive S corp or partnership income potentially be hit by the NIIT?  My reading of [this IRS FAQ](https://www.irs.gov/uac/newsroom/net-investment-income-tax-faqs) suggests it would be.

**Comment by codykallen** [comment]
Yes, that is technically correct. The IRS makes a legal distinction between active and passive S corp/partnership income, and the NIIT does not apply to active S corp/partnership income. However, we don't have the ability to distinguish between the two. Tax-Calculator applies the NIIT to (e02000 - e26270). This means that we are effectively just treating all S corp and partnership income as active.

**Comment by jdebacker** [comment]
Ok - got it.  Thanks.

**Pull request merged**
