### PR TITLE
formatting dataframes for json tables

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
Further develops helper functions for converting dataframes by asset, industry to json list of lists.

Current status is that the asset dataframe converter is working, but the industry dataframe does not have all the expected column names from the `param_defaults/btax_results_by_industry.json`.  Here is the set of columns that are missing from the dataframe for industry:

```
KeyError: "[u'NAICS' u'metr_nc' u'metr_c_d' u'metr_c' u'metr_c_e'] not in index"
```

Also note that this PR reformats the `param_defaults/btax_results_by_*.json` to be list data structures instead of dictionaries (so we can preserve column order).  @jdebacker Can you do a PR to against this one to order the columns in the `btax_results_by*.json` files as they should be in the final output and also look into the missing columns issue?

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
We should also look into this warning:
[https://travis-ci.org/open-source-economics/B-Tax/builds/151563753#L677](https://travis-ci.org/open-source-economics/B-Tax/builds/151563753#L677) regarding setting on a slice, which may result in an assignment not actually happening.

**Comment by jdebacker** [comment]
@PeterDSteinberg, just getting to this.  I've fixed column names and other open PR will fix missing columns.  Will work on ordering.  But do have a question - not all columns will display  in table at once.   @talumbau  and @brendanco are working on buttons in the UI that select which columns will display.  Shall I just organize the columns relative to the ones that will be displayed together?

This might not be clear, so let me know and I can follow up with more detail.

**Comment by PeterDSteinberg** [comment]
@jdebacker To each of the dictionaries in the column headers meta jsons, can you also add a "table_id" key.  It is assumed then that all the columns sharing a "table_id" are given in order.  Then we can better break up the table display.  Example:
```
  [
     "z_c_d",
     {
       "col_label": "NPV of depreciation deductions, corporate debt financed investment",
       "name": "z_c_d",
       "table_id": "group_1",
       "tooltip": "Net Present value of depreciation deductions, corporate debt financed investment"
     }
   ]
```

**Comment by jdebacker** [comment]
@PeterDSteinberg, I just opened a PR hoping to merge the requested updates to the json files into your branch.

**Comment by jdebacker** [comment]
@PeterDSteinberg , that set with copy warning appears to be coming from the final line in format_output.py, which is where a pandas dataframe is saved to a csv.  I'm not sure why this would trigger such warning or how to avoid.

**Pull request merged**
